// Generated by scripts/build.mjs from content/apps.json.
export const apps = [
  {
    "id": "altus-lotviewer",
    "index": 1,
    "sourceKey": "parser_tab",
    "name": "Altus LotViewer",
    "category": "Expedition I - Altus",
    "description": "Lot history analysis.",
    "visualType": "lot_trace",
    "accent": "#d89b75",
    "pose": [
      -9,
      23,
      -2
    ],
    "pace": 0.52,
    "heroImage": "assets/artifacts/apps/altus-lotviewer/hero.webp",
    "responsiveImage": "assets/artifacts/apps/altus-lotviewer/hero-1280.webp",
    "thumbnail": "assets/artifacts/apps/altus-lotviewer/thumbnail.webp",
    "width": 2048,
    "height": 1104,
    "detailImages": [
      {
        "src": "assets/artifacts/apps/altus-lotviewer/detail-01.webp",
        "width": 1475,
        "height": 442,
        "label": "Lot history rows",
        "region": {
          "left": 348,
          "top": 243,
          "width": 1475,
          "height": 442
        }
      }
    ],
    "exampleImage": null,
    "captureNote": "Demo lot history",
    "sourceQuality": "jpeg-derived-archive",
    "needsRecapture": true
  },
  {
    "id": "altus-anko-viewer",
    "index": 2,
    "sourceKey": "altusanko_tab",
    "name": "Altus ANKO Viewer",
    "category": "Expedition I - Altus",
    "description": "ANKO schedule retrieval.",
    "visualType": "anko_schedule",
    "accent": "#d89b75",
    "pose": [
      8,
      -20,
      2
    ],
    "pace": 0.62,
    "heroImage": "assets/artifacts/apps/altus-anko-viewer/hero.webp",
    "responsiveImage": "assets/artifacts/apps/altus-anko-viewer/hero-1280.webp",
    "thumbnail": "assets/artifacts/apps/altus-anko-viewer/thumbnail.webp",
    "width": 2048,
    "height": 1104,
    "detailImages": [
      {
        "src": "assets/artifacts/apps/altus-anko-viewer/detail-01.webp",
        "width": 1720,
        "height": 397,
        "label": "Reactor schedule",
        "region": {
          "left": 164,
          "top": 144,
          "width": 1720,
          "height": 397
        }
      }
    ],
    "exampleImage": null,
    "captureNote": "Demo schedule",
    "sourceQuality": "jpeg-derived-archive",
    "needsRecapture": true
  },
  {
    "id": "altus-wafercount",
    "index": 3,
    "sourceKey": "wafercount_tab",
    "name": "Altus WaferCount",
    "category": "Expedition I - Altus",
    "description": "Wafer loading planner.",
    "visualType": "wafer_grid",
    "accent": "#d89b75",
    "pose": [
      -12,
      14,
      -4
    ],
    "pace": 0.58,
    "heroImage": "assets/artifacts/apps/altus-wafercount/hero.webp",
    "responsiveImage": "assets/artifacts/apps/altus-wafercount/hero-1280.webp",
    "thumbnail": "assets/artifacts/apps/altus-wafercount/thumbnail.webp",
    "width": 2048,
    "height": 1104,
    "detailImages": [
      {
        "src": "assets/artifacts/apps/altus-wafercount/detail-01.webp",
        "width": 1126,
        "height": 442,
        "label": "Loading overview",
        "region": {
          "left": 123,
          "top": 132,
          "width": 1126,
          "height": 442
        }
      }
    ],
    "exampleImage": null,
    "captureNote": "Demo loading values",
    "sourceQuality": "jpeg-derived-archive",
    "needsRecapture": true
  },
  {
    "id": "topotracer",
    "index": 4,
    "sourceKey": "topotracer_tab",
    "name": "TopoTracer",
    "category": "Expedition II - Interstice",
    "description": "Contour and topography plots.",
    "visualType": "topography",
    "accent": "#d89b75",
    "pose": [
      16,
      -24,
      3
    ],
    "pace": 0.68,
    "heroImage": "assets/artifacts/apps/topotracer/hero.webp",
    "responsiveImage": "assets/artifacts/apps/topotracer/hero-1280.webp",
    "thumbnail": "assets/artifacts/apps/topotracer/thumbnail.webp",
    "width": 2048,
    "height": 1104,
    "detailImages": [
      {
        "src": "assets/artifacts/apps/topotracer/detail-01.webp",
        "width": 819,
        "height": 662,
        "label": "Topography and contours",
        "region": {
          "left": 164,
          "top": 309,
          "width": 819,
          "height": 662
        }
      }
    ],
    "exampleImage": null,
    "captureNote": "Demo contour plot",
    "sourceQuality": "jpeg-derived-archive",
    "needsRecapture": true
  },
  {
    "id": "papyrus-reader",
    "index": 5,
    "sourceKey": "xml_tab",
    "name": "Papyrus Reader",
    "category": "Expedition II - Interstice",
    "description": "XML, EPI, and text reader.",
    "visualType": "document",
    "accent": "#d89b75",
    "pose": [
      -4,
      28,
      0
    ],
    "pace": 0.52,
    "heroImage": "assets/artifacts/apps/papyrus-reader/hero.webp",
    "responsiveImage": "assets/artifacts/apps/papyrus-reader/hero-1280.webp",
    "thumbnail": "assets/artifacts/apps/papyrus-reader/thumbnail.webp",
    "width": 3840,
    "height": 2160,
    "detailImages": [
      {
        "src": "assets/artifacts/apps/papyrus-reader/detail-01.webp",
        "width": 3149,
        "height": 238,
        "label": "Document comparison controls",
        "region": {
          "left": 307,
          "top": 216,
          "width": 3149,
          "height": 238
        }
      }
    ],
    "exampleImage": "assets/artifacts/apps/papyrus-reader/example.webp",
    "captureNote": "Entry workspace",
    "sourceQuality": "native-4k",
    "needsRecapture": false
  },
  {
    "id": "spc-pathfinder",
    "index": 6,
    "sourceKey": "path_tab",
    "name": "SPC Pathfinder",
    "category": "Expedition II - Interstice",
    "description": "SPC chart finder.",
    "visualType": "pathfinder",
    "accent": "#d89b75",
    "pose": [
      9,
      -17,
      -2
    ],
    "pace": 0.62,
    "heroImage": "assets/artifacts/apps/spc-pathfinder/hero.webp",
    "responsiveImage": "assets/artifacts/apps/spc-pathfinder/hero-1280.webp",
    "thumbnail": "assets/artifacts/apps/spc-pathfinder/thumbnail.webp",
    "width": 2048,
    "height": 1104,
    "detailImages": [
      {
        "src": "assets/artifacts/apps/spc-pathfinder/detail-01.webp",
        "width": 860,
        "height": 607,
        "label": "Chart index",
        "region": {
          "left": 1044,
          "top": 276,
          "width": 860,
          "height": 607
        }
      }
    ],
    "exampleImage": null,
    "captureNote": "Example chart index",
    "sourceQuality": "jpeg-derived-archive",
    "needsRecapture": true
  },
  {
    "id": "gan-met-compiler",
    "index": 7,
    "sourceKey": "metro_tab",
    "name": "GaN Met Compiler",
    "category": "Expedition III - GaN EPI",
    "description": "Metrology report compiler.",
    "visualType": "metrology",
    "accent": "#d89b75",
    "pose": [
      12,
      22,
      2
    ],
    "pace": 0.58,
    "heroImage": "assets/artifacts/apps/gan-met-compiler/hero.webp",
    "responsiveImage": "assets/artifacts/apps/gan-met-compiler/hero-1280.webp",
    "thumbnail": "assets/artifacts/apps/gan-met-compiler/thumbnail.webp",
    "width": 2048,
    "height": 1104,
    "detailImages": [
      {
        "src": "assets/artifacts/apps/gan-met-compiler/detail-01.webp",
        "width": 1720,
        "height": 287,
        "label": "Compilation workflow",
        "region": {
          "left": 164,
          "top": 773,
          "width": 1720,
          "height": 287
        }
      }
    ],
    "exampleImage": null,
    "captureNote": "Entry workspace",
    "sourceQuality": "jpeg-derived-archive",
    "needsRecapture": true
  },
  {
    "id": "gan-temp-diagnoser",
    "index": 8,
    "sourceKey": "pyra_tab",
    "name": "GaN Temp Diagnoser",
    "category": "Expedition III - GaN EPI",
    "description": "Temperature drift diagnosis.",
    "visualType": "thermal",
    "accent": "#d89b75",
    "pose": [
      -10,
      -18,
      -3
    ],
    "pace": 0.68,
    "heroImage": "assets/artifacts/apps/gan-temp-diagnoser/hero.webp",
    "responsiveImage": "assets/artifacts/apps/gan-temp-diagnoser/hero-1280.webp",
    "thumbnail": "assets/artifacts/apps/gan-temp-diagnoser/thumbnail.webp",
    "width": 3840,
    "height": 2160,
    "detailImages": [
      {
        "src": "assets/artifacts/apps/gan-temp-diagnoser/detail-01.webp",
        "width": 1536,
        "height": 1145,
        "label": "Observation controls",
        "region": {
          "left": 269,
          "top": 432,
          "width": 1536,
          "height": 1145
        }
      }
    ],
    "exampleImage": "assets/artifacts/apps/gan-temp-diagnoser/example.webp",
    "captureNote": "Entry workspace",
    "sourceQuality": "native-4k",
    "needsRecapture": false
  },
  {
    "id": "aix-dt-assistant",
    "index": 9,
    "sourceKey": "dt_tab",
    "name": "AIX ΔT Assistant",
    "category": "Expedition III - GaN EPI",
    "description": "Wafer-to-wafer dT checks.",
    "visualType": "delta",
    "accent": "#d89b75",
    "pose": [
      14,
      24,
      1
    ],
    "pace": 0.52,
    "heroImage": "assets/artifacts/apps/aix-dt-assistant/hero.webp",
    "responsiveImage": "assets/artifacts/apps/aix-dt-assistant/hero-1280.webp",
    "thumbnail": "assets/artifacts/apps/aix-dt-assistant/thumbnail.webp",
    "width": 3840,
    "height": 2160,
    "detailImages": [
      {
        "src": "assets/artifacts/apps/aix-dt-assistant/detail-01.webp",
        "width": 2074,
        "height": 1534,
        "label": "Mapping geometry",
        "region": {
          "left": 1459,
          "top": 367,
          "width": 2074,
          "height": 1534
        }
      }
    ],
    "exampleImage": "assets/artifacts/apps/aix-dt-assistant/example.webp",
    "captureNote": "Entry workspace",
    "sourceQuality": "native-4k",
    "needsRecapture": false
  },
  {
    "id": "lt-zone-assistant",
    "index": 10,
    "sourceKey": "laytec_tab",
    "name": "LT Zone Assistant",
    "category": "Expedition III - GaN EPI",
    "description": "LayTec zone mapping.",
    "visualType": "zone_map",
    "accent": "#d89b75",
    "pose": [
      18,
      -16,
      -4
    ],
    "pace": 0.62,
    "heroImage": "assets/artifacts/apps/lt-zone-assistant/hero.webp",
    "responsiveImage": "assets/artifacts/apps/lt-zone-assistant/hero-1280.webp",
    "thumbnail": "assets/artifacts/apps/lt-zone-assistant/thumbnail.webp",
    "width": 2048,
    "height": 1104,
    "detailImages": [
      {
        "src": "assets/artifacts/apps/lt-zone-assistant/detail-01.webp",
        "width": 1044,
        "height": 828,
        "label": "Inner and outer zones",
        "region": {
          "left": 737,
          "top": 132,
          "width": 1044,
          "height": 828
        }
      }
    ],
    "exampleImage": null,
    "captureNote": "Zone geometry",
    "sourceQuality": "jpeg-derived-archive",
    "needsRecapture": true
  },
  {
    "id": "gan-xml-assistant",
    "index": 11,
    "sourceKey": "xmlll_tab",
    "name": "GaN XML Assistant",
    "category": "Expedition III - GaN EPI",
    "description": "Devices.XML comparison.",
    "visualType": "xml_compare",
    "accent": "#d89b75",
    "pose": [
      -8,
      26,
      0
    ],
    "pace": 0.58,
    "heroImage": "assets/artifacts/apps/gan-xml-assistant/hero.webp",
    "responsiveImage": "assets/artifacts/apps/gan-xml-assistant/hero-1280.webp",
    "thumbnail": "assets/artifacts/apps/gan-xml-assistant/thumbnail.webp",
    "width": 3840,
    "height": 2160,
    "detailImages": [
      {
        "src": "assets/artifacts/apps/gan-xml-assistant/detail-01.webp",
        "width": 3149,
        "height": 151,
        "label": "XML comparison controls",
        "region": {
          "left": 346,
          "top": 227,
          "width": 3149,
          "height": 151
        }
      }
    ],
    "exampleImage": "assets/artifacts/apps/gan-xml-assistant/example.webp",
    "captureNote": "Entry workspace",
    "sourceQuality": "native-4k",
    "needsRecapture": false
  },
  {
    "id": "magus-spc-gan",
    "index": 12,
    "sourceKey": "dnd_tab",
    "name": "Magus SPC (GaN)",
    "category": "Expedition IV - Planetfall",
    "description": "GaN SPC release review.",
    "visualType": "spc_gan",
    "accent": "#d89b75",
    "pose": [
      6,
      -22,
      2
    ],
    "pace": 0.68,
    "heroImage": "assets/artifacts/apps/magus-spc-gan/hero.webp",
    "responsiveImage": "assets/artifacts/apps/magus-spc-gan/hero-1280.webp",
    "thumbnail": "assets/artifacts/apps/magus-spc-gan/thumbnail.webp",
    "width": 3840,
    "height": 2160,
    "detailImages": [
      {
        "src": "assets/artifacts/apps/magus-spc-gan/detail-01.webp",
        "width": 3379,
        "height": 259,
        "label": "SPC review controls",
        "region": {
          "left": 230,
          "top": 259,
          "width": 3379,
          "height": 259
        }
      }
    ],
    "exampleImage": "assets/artifacts/apps/magus-spc-gan/example.webp",
    "captureNote": "Entry workspace",
    "sourceQuality": "native-4k",
    "needsRecapture": false
  },
  {
    "id": "magus-spc-legacy",
    "index": 13,
    "sourceKey": "dnd2_tab",
    "name": "Magus SPC (Legacy)",
    "category": "Expedition IV - Planetfall",
    "description": "Legacy SPC release review.",
    "visualType": "spc_legacy",
    "accent": "#d89b75",
    "pose": [
      -5,
      18,
      -1
    ],
    "pace": 0.52,
    "heroImage": "assets/artifacts/apps/magus-spc-legacy/hero.webp",
    "responsiveImage": "assets/artifacts/apps/magus-spc-legacy/hero-1280.webp",
    "thumbnail": "assets/artifacts/apps/magus-spc-legacy/thumbnail.webp",
    "width": 3840,
    "height": 2160,
    "detailImages": [
      {
        "src": "assets/artifacts/apps/magus-spc-legacy/detail-01.webp",
        "width": 3379,
        "height": 259,
        "label": "Legacy review controls",
        "region": {
          "left": 230,
          "top": 259,
          "width": 3379,
          "height": 259
        }
      }
    ],
    "exampleImage": "assets/artifacts/apps/magus-spc-legacy/example.webp",
    "captureNote": "Entry workspace",
    "sourceQuality": "native-4k",
    "needsRecapture": false
  },
  {
    "id": "anko-helper",
    "index": 14,
    "sourceKey": "ankohelper_tab",
    "name": "ANKO Helper",
    "category": "Expedition IV - Planetfall",
    "description": "ANKO status and due dates.",
    "visualType": "anko_cycle",
    "accent": "#d89b75",
    "pose": [
      10,
      -24,
      3
    ],
    "pace": 0.62,
    "heroImage": "assets/artifacts/apps/anko-helper/hero.webp",
    "responsiveImage": "assets/artifacts/apps/anko-helper/hero-1280.webp",
    "thumbnail": "assets/artifacts/apps/anko-helper/thumbnail.webp",
    "width": 2048,
    "height": 1104,
    "detailImages": [
      {
        "src": "assets/artifacts/apps/anko-helper/detail-01.webp",
        "width": 963,
        "height": 397,
        "label": "Schedule report",
        "region": {
          "left": 1024,
          "top": 431,
          "width": 963,
          "height": 397
        }
      }
    ],
    "exampleImage": null,
    "captureNote": "Demo report",
    "sourceQuality": "jpeg-derived-archive",
    "needsRecapture": true
  },
  {
    "id": "lt-report-compiler",
    "index": 15,
    "sourceKey": "sap_tab",
    "name": "LT Report Compiler",
    "category": "Expedition IV - Planetfall",
    "description": "LayTec report compilation.",
    "visualType": "laytec_report",
    "accent": "#d89b75",
    "pose": [
      -12,
      20,
      -2
    ],
    "pace": 0.58,
    "heroImage": "assets/artifacts/apps/lt-report-compiler/hero.webp",
    "responsiveImage": "assets/artifacts/apps/lt-report-compiler/hero-1280.webp",
    "thumbnail": "assets/artifacts/apps/lt-report-compiler/thumbnail.webp",
    "width": 2048,
    "height": 1104,
    "detailImages": [
      {
        "src": "assets/artifacts/apps/lt-report-compiler/detail-01.webp",
        "width": 1802,
        "height": 243,
        "label": "Report compilation workflow",
        "region": {
          "left": 123,
          "top": 795,
          "width": 1802,
          "height": 243
        }
      }
    ],
    "exampleImage": null,
    "captureNote": "Entry workspace",
    "sourceQuality": "jpeg-derived-archive",
    "needsRecapture": true
  },
  {
    "id": "metria-spc",
    "index": 16,
    "sourceKey": "plessey_spc_tab",
    "name": "Metria SPC",
    "category": "Expedition IV - Planetfall",
    "description": "Interactive multi-parameter equipment SPC.",
    "visualType": "process_spc",
    "accent": "#d89b75",
    "pose": [
      14,
      -18,
      1
    ],
    "pace": 0.68,
    "heroImage": "assets/artifacts/apps/metria-spc/hero.webp",
    "responsiveImage": "assets/artifacts/apps/metria-spc/hero-1280.webp",
    "thumbnail": "assets/artifacts/apps/metria-spc/thumbnail.webp",
    "width": 3840,
    "height": 2160,
    "detailImages": [
      {
        "src": "assets/artifacts/apps/metria-spc/detail-01.webp",
        "width": 3226,
        "height": 756,
        "label": "Aligned control charts",
        "region": {
          "left": 307,
          "top": 864,
          "width": 3226,
          "height": 756
        }
      }
    ],
    "exampleImage": null,
    "captureNote": "Sample data",
    "sourceQuality": "native-4k",
    "needsRecapture": false
  }
];
