import fs from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {esc,icon,nativeShell,themeControl} from './native-ui.mjs';
const model=JSON.parse(await fs.readFile('content/apps.json','utf8'));
const num=n=>String(n).padStart(2,'0');
const image=(capture,name,feature=false)=>`<img src="${capture.base}/1280.webp" srcset="${(capture.sources||[]).map(s=>`${s.src} ${s.width}w`).join(',')}" sizes="${feature?'90vw':'(max-width:760px) 94vw, (max-width:1300px) 46vw, 840px'}" width="${capture.width||10240}" height="${capture.height||5520}" loading="lazy" decoding="async" alt="${esc(name)} — ${esc(capture.caption)}">`;
function gallery(app,expedition,index){
 const first=app.images.findIndex(c=>c.theme==='pentimento'),capture=app.images[first];
 return `<article class="gallery-app${app.id==='topotracer'||app.id==='data-lens'?' gallery-feature':''}" data-gallery-app="${app.id}" data-initial-slide="${first}" id="${expedition.id}-${app.id}" aria-labelledby="${expedition.id}-${app.id}-title"><header><div><span class="app-index">${num(app.index)}</span><h3 id="${expedition.id}-${app.id}-title">${esc(app.name)}</h3></div><button type="button" class="open-capture" data-lightbox aria-label="Enlarge ${esc(app.name)} screenshot" aria-haspopup="dialog" disabled>${icon('expand')}</button></header><button type="button" class="gallery-image" data-lightbox aria-label="Enlarge ${esc(app.name)} screenshot" aria-haspopup="dialog" disabled>${image(capture,app.name,app.id==='topotracer'||app.id==='data-lens')}</button><div class="gallery-navigation"><span class="gallery-count" aria-live="off">${num(first+1)} <span>/ ${num(app.images.length)}</span></span><div class="gallery-progress" aria-hidden="true"><span></span></div><button type="button" class="gallery-play" aria-label="Pause ${esc(app.name)} slideshow" aria-pressed="false" disabled>${icon('pause',16)}</button><button type="button" data-previous aria-label="Previous ${esc(app.name)} screenshot" disabled>${icon('back',18)}</button><button type="button" data-next aria-label="Next ${esc(app.name)} screenshot" disabled>${icon('next',18)}</button></div><div class="gallery-caption"><p>${esc(app.purpose)}</p><span data-slide-caption>${esc(capture.caption)} · Pentimento</span></div><noscript><div class="capture-fallback">${app.images.map((c,i)=>`<a href="${c.base}/full.webp">Capture ${i+1}</a>`).join('')}</div></noscript></article>`;
}
const expeditions=model.expeditions.map(e=>`<section class="gallery-expedition" id="${e.id}" data-mode="${e.mode}" aria-labelledby="${e.id}-title"><header class="expedition-heading"><p class="eyebrow">Expedition ${e.numeral}<span>${num(e.apps.length)} applications</span></p><h2 id="${e.id}-title">${esc(e.name)}</h2></header><div class="gallery-grid">${e.apps.map((id,i)=>gallery(model.apps.find(a=>a.id===id),e,i)).join('')}</div></section>`).join('');
const html=`<!doctype html>
<html lang="en" data-theme="pentimento" data-mode="pentimento">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Artifacts by Gene</title><meta name="description" content="Explore ARTIFACTS: engineering applications for analysis, diagnosis, comparison and reporting. Developed by Gene (Wei Gene Khor)."><link rel="canonical" href="https://artifactsbygene.com/"><meta name="theme-color" content="#0d0e12"><meta property="og:title" content="Artifacts by Gene"><meta property="og:description" content="Built for engineering that has to be right."><meta property="og:type" content="website"><meta property="og:url" content="https://artifactsbygene.com/"><meta property="og:image" content="https://artifactsbygene.com/assets/social-preview.png"><link rel="icon" type="image/svg+xml" href="assets/brand/artifacts-symbol.svg"><link rel="stylesheet" href="tokens.css"><link rel="stylesheet" href="site.css"><link rel="stylesheet" href="shell.css"><script>try{for(const key of ['theme','mode']){const value=localStorage.getItem('artifacts-'+key);if((key==='theme'?['origin','pentimento']:['legacy','pentimento']).includes(value))document.documentElement.dataset[key]=value;}}catch{}document.documentElement.classList.add('js');</script></head>
<body><a class="skip-link" href="#principle">Skip interactive application</a><main>${nativeShell(model)}
<nav class="website-nav" aria-label="Website navigation"><a href="#top" class="website-brand"><img src="assets/brand/artifacts-symbol.svg" width="21" height="21" alt=""><span>ARTIFACTS</span></a><div><a href="#applications">Applications</a><a href="#gene">Gene</a>${themeControl('Website')}</div></nav>
<section class="principle page-width" id="principle"><p class="eyebrow">The principle</p><h1>What repeated was automated.<br><span>What stood in the way was rebuilt.</span></h1><p class="principle-support">ARTIFACTS removes unnecessary friction from engineering work, with tools for comparison, diagnosis, analysis and reporting.</p></section>
<section class="applications page-width" id="applications" aria-label="Application galleries"><header class="collection-heading"><div><p class="eyebrow">The applications</p><p class="collection-summary">Working software.<br><span>In full view.</span></p></div><div class="collection-controls"><span>Explore both editions</span><div class="edition-picker" role="group" aria-label="Gallery edition">${model.modes.map(m=>`<button type="button" data-select-mode="${m.id}" aria-pressed="${m.id==='pentimento'}">${m.name}<span>${m.range}</span></button>`).join('')}</div><small>17 applications across the two editions.</small></div></header>${expeditions}</section>
<section class="authorship page-width" id="gene"><p class="eyebrow">Developed by</p><div><h2>Gene <span>(Wei Gene Khor)</span></h2><a href="mailto:weigenekhor@gmail.com">weigenekhor@gmail.com ${icon('external',16)}</a><a href="https://www.linkedin.com/in/weigenekhor/" target="_blank" rel="noopener noreferrer">LinkedIn ${icon('external',16)}</a></div></section>
<footer class="ending page-width"><img src="assets/brand/artifacts-symbol.svg" width="48" height="48" alt=""><p class="ending-name">ARTIFACTS</p><p>Built for engineering that has to be right.</p></footer></main>
<dialog class="lightbox" id="capture-viewer" aria-labelledby="viewer-title"><div class="lightbox-bar"><div><h2 id="viewer-title"></h2><p id="viewer-caption"></p></div><div><span id="viewer-count"></span>${themeControl('Image viewer')}<button type="button" data-viewer-close aria-label="Close image viewer">${icon('close')}</button></div></div><div class="lightbox-stage"><button type="button" data-viewer-prev aria-label="Previous screenshot">${icon('back')}</button><div class="lightbox-image-wrap"><img id="viewer-image" alt=""><span class="image-loading" role="status" hidden>Loading capture…</span></div><button type="button" data-viewer-next aria-label="Next screenshot">${icon('next')}</button></div><div class="lightbox-footer"><span>Original application capture</span><a id="viewer-original" target="_blank" rel="noopener">Full resolution ${icon('external',16)}</a></div></dialog>
<dialog id="preview-help" class="help-dialog" aria-labelledby="preview-title"><h2 id="preview-title">Explore ARTIFACTS.</h2><p>Open an application, switch editions and try the interface controls. File processing and engineering calculations run in the desktop application.</p><p>The galleries below show the applications in use.</p><form method="dialog"><button>Continue exploring</button></form></dialog>
<noscript><style>.gallery-expedition[data-mode]{display:block!important}.app-sidebar,.window-controls,.module-details{display:none!important}.app-home{height:auto}.app-shell{height:auto;min-height:0}.app-body{min-height:0}.app-content{overflow:hidden}.native-background{display:none}.home-cards{display:flex!important;flex-wrap:wrap;width:auto}.app-tile{pointer-events:none}.hero-edge{height:auto;padding:16px}.gallery-navigation button,.open-capture,.edition-picker,.theme-control{display:none}.gallery-image{cursor:default}</style><p class="noscript-note">The galleries remain available without JavaScript. Enable JavaScript to explore the interactive application shell.</p></noscript>
<script type="application/json" id="artifacts-data">${JSON.stringify(model).replaceAll('<','\\u003c')}</script><script type="module" src="site.js"></script></body></html>`;
let output=html;
for(const file of ['tokens.css','site.css','shell.css','site.js']){
 const hash=createHash('sha256').update(await fs.readFile(file)).digest('hex').slice(0,10);
 output=output.replaceAll(`"${file}"`,`"${file}?v=${hash}"`);
}
await fs.writeFile('index.html',output);
console.log(`Built native ARTIFACTS: ${model.apps.length} shells, ${model.expeditions.length} Expeditions, ${model.apps.reduce((n,a)=>n+a.images.length,0)} screenshots.`);
