import fs from "node:fs";
const { apps } = JSON.parse(fs.readFileSync("content/apps.json", "utf8"));
const esc = (s) =>
  s.replace(
    /[&<>\"]/g,
    (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c],
  );
const image = (a, cls = "") =>
  `<img class="${cls}" data-src="${a.heroImage}" data-srcset="${a.responsiveImage} 1280w, ${a.heroImage} ${a.width}w" width="${a.width}" height="${a.height}" alt="${esc(a.name)} — ${esc(a.captureNote.toLowerCase())}" decoding="async">`;
const groups = [...new Set(apps.map((a) => a.category))];
const navigation = groups
  .map(
    (group, g) =>
      `<div class="index-group"><span class="group-label">${esc(group.replace(" - ", " / "))}</span>${apps
        .filter((a) => a.category === group)
        .map(
          (a) =>
            `<a href="#app-${a.id}" data-app="${a.index - 1}"><span>${String(a.index).padStart(2, "0")}</span>${esc(a.name)}<i aria-hidden="true"></i></a>`,
        )
        .join("")}</div>`,
  )
  .join("");
const articles = apps
  .map(
    (
      a,
      i,
    ) => `<article class="artifact" id="app-${a.id}" data-index="${i}" data-visual="${a.visualType}" aria-labelledby="name-${a.id}">
 <div class="artifact-copy"><p class="eyebrow">${esc(a.category.replace(" - ", " / "))}</p><h3 id="name-${a.id}">${esc(a.name)}</h3><p class="app-description">${esc(a.description)}</p></div>
 <div class="camera-world"><div class="artifact-pose"><a class="screen-object" data-inspect="${i}" href="${a.heroImage}" aria-label="Inspect ${esc(a.name)}">${image(a, "screen-image")}<noscript><img src="${a.heroImage}" width="${a.width}" height="${a.height}" alt="${esc(a.name)} interface" loading="lazy"></noscript><span class="screen-reflection" aria-hidden="true"></span></a><div class="screen-shards" aria-hidden="true">${[0, 1, 2].map((n) => `<div class="screen-shard" style="--slice:${n}">${image(a)}</div>`).join("")}</div></div>
 <div class="extracted-detail" aria-hidden="true"><img data-src="${a.detailImages[0].src}" width="${a.detailImages[0].width}" height="${a.detailImages[0].height}" alt="" decoding="async"><span>${esc(a.detailImages[0].label)}</span></div></div>
 <div class="artifact-caption"><span>${esc(a.captureNote)}</span><a href="${a.heroImage}" data-inspect="${i}">Inspect interface <span aria-hidden="true">↗</span></a></div>
</article>`,
  )
  .join("\n");
const constellation = apps
  .map(
    (a, i) =>
      `<a href="#app-${a.id}" data-app="${i}" class="constellation-plane" style="--n:${i}"><img src="${a.thumbnail}" width="${a.width}" height="${a.height}" alt="${esc(a.name)}" loading="lazy" decoding="async"><span>${String(i + 1).padStart(2, "0")} / ${esc(a.name)}</span></a>`,
  )
  .join("");
let template = fs.readFileSync("content/page.html", "utf8");
for (const [token, html] of Object.entries({
  EXPEDITION_LINKS: groups
    .map((group, g) => {
      const members = apps.filter((a) => a.category === group);
      return `<a href="#app-${members[0].id}" data-app="${members[0].index - 1}"><span>0${g + 1} / ${members.length} APPLICATIONS</span>${esc(group.split(" - ")[1])}<i aria-hidden="true">↗</i></a>`;
    })
    .join(""),
  APP_INDEX: navigation,
  APP_SCENES: articles,
  CONSTELLATION: constellation,
  REAL_LOGO: fs
    .readFileSync("assets/brand/artifacts-symbol.svg", "utf8")
    .replace("<svg ", '<svg class="hero-mark" aria-hidden="true" '),
}))
  template = template.replace("<!-- " + token + " -->", html);
fs.writeFileSync("index.html", template);
// Generated from the same catalogue as semantic HTML; there is one source of truth.
fs.writeFileSync(
  "js/apps.js",
  "// Generated by scripts/build.mjs from content/apps.json.\nexport const apps = " +
    JSON.stringify(
      apps.map(
        ({ sourceFile, sourceSha256, sourcePixelSha256, heroSha256, ...app }) =>
          app,
      ),
      null,
      2,
    ) +
    ";\n",
);
console.log(
  `Built ${apps.length} real applications across ${groups.length} source categories.`,
);
