import fs from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {esc,icon,nativeShell} from './native-ui.mjs';
const model=JSON.parse(await fs.readFile('content/apps.json','utf8'));
import {principleSection} from './principles.mjs';
const num=n=>String(n).padStart(2,'0');
model.apps.sort((a,b)=>a.order-b.order);
const homeLayouts=JSON.parse(await fs.readFile('content/home-layouts.json','utf8'));
const panelReferences=JSON.parse(await fs.readFile('content/panel-reference.json','utf8'));
const image=(capture,name,feature=false)=>`<img src="${capture.base}/1280.webp" srcset="${(capture.sources||[]).map(s=>`${s.src} ${s.width}w`).join(',')}" sizes="${feature?'90vw':'(max-width:760px) 94vw, (max-width:1300px) 46vw, 840px'}" width="${capture.width||10240}" height="${capture.height||5520}" loading="lazy" decoding="async" alt="${esc(name)} — ${esc(capture.caption)}">`;
function gallery(app,index){
 const captures=app.images.filter(c=>c.theme==='pentimento'),first=0,capture=captures[0];
 return `<article class="gallery-app${app.featured?' gallery-feature':app.standalone?' gallery-standard-wide':''}" data-gallery-app="${app.id}" data-initial-slide="${first}" id="app-${app.id}" aria-labelledby="app-${app.id}-title"><header><div><span class="app-index">${num(index+1)}</span><h3 id="app-${app.id}-title">${esc(app.name)}</h3></div><button type="button" class="open-capture" data-lightbox aria-label="Enlarge ${esc(app.name)} screenshot" aria-haspopup="dialog" disabled>${icon('expand')}</button></header><button type="button" class="gallery-image" data-advance aria-label="Next ${esc(app.name)} screenshot" disabled>${image(capture,app.name,app.featured)}</button><div class="gallery-navigation"><span class="gallery-count" aria-live="off">${num(first+1)} <span>/ ${num(captures.length)}</span></span><div class="gallery-progress" aria-hidden="true"><span></span></div><button type="button" class="gallery-play" aria-label="Pause ${esc(app.name)} slideshow" aria-pressed="false" disabled>${icon('pause',16)}</button><button type="button" data-previous aria-label="Previous ${esc(app.name)} screenshot" disabled>${icon('back',18)}</button><button type="button" data-next aria-label="Next ${esc(app.name)} screenshot" disabled>${icon('next',18)}</button></div><div class="gallery-caption"><p>${esc(app.purpose)}</p><span data-slide-caption>${esc(capture.caption)}</span></div><noscript><div class="capture-fallback">${app.images.map((c,i)=>`<a href="${c.base}/full.webp">Capture ${i+1}</a>`).join('')}</div></noscript></article>`;
}
for(let i=0;i<model.apps.length;){
 if(model.apps[i].featured){i++;continue;}
 let end=i;while(end<model.apps.length&&!model.apps[end].featured)end++;
 if((end-i)%2)model.apps[end-1].standalone=true;
 i=end;
}
const html=`<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Artifacts by Gene</title><meta name="description" content="Explore ARTIFACTS: engineering applications for analysis, diagnosis, comparison and reporting. Developed by Gene (Wei Gene Khor)."><link rel="canonical" href="https://artifactsbygene.com/"><meta name="theme-color" content="#101113"><meta property="og:title" content="Artifacts by Gene"><meta property="og:description" content="A coherent system of tools for analysis, diagnosis, automation, and engineering workflows."><meta property="og:type" content="website"><meta property="og:url" content="https://artifactsbygene.com/"><meta property="og:image" content="https://artifactsbygene.com/assets/social-preview.png"><link rel="icon" type="image/svg+xml" href="assets/brand/artifacts-symbol.svg"><link rel="stylesheet" href="tokens.css"><link rel="stylesheet" href="site.css"><link rel="stylesheet" href="shell.css"><link rel="stylesheet" href="thinking.css"><script>document.documentElement.classList.add('js');</script></head>
<body id="top"><a class="skip-link" href="#applications">Skip to applications</a>
<nav class="website-nav page-width" aria-label="Website navigation"><a href="#top" class="website-brand"><img src="assets/brand/artifacts-symbol.svg" width="25" height="25" alt=""><span>ARTIFACTS</span></a><div><a href="#applications">Applications</a><a href="#gene">About</a></div></nav>
<main><div class="experience-opening"><section class="hero" aria-labelledby="hero-heading"><div class="hero-intro page-width"><p class="eyebrow">ARTIFACTS / ENGINEERING SYSTEM</p><h1 id="hero-heading">ARTIFACTS</h1></div>${nativeShell(model,homeLayouts)}</section>
${principleSection()}</div>
<section class="applications page-width" id="applications" aria-labelledby="collection-heading"><header class="collection-heading"><div><p class="eyebrow">The collection</p><h2 id="collection-heading">Applications</h2></div><p><span>${num(model.apps.length)}</span> purpose-built applications</p></header><div class="gallery-grid">${model.apps.map(gallery).join('')}</div></section>
<section class="authorship page-width" id="gene" aria-labelledby="author-statement"><div class="author-ghost" aria-hidden="true"><div class="author-ghost-window"><img class="author-ghost-field" src="assets/native/layouts/pentimento-pentimento-closed-field.webp" alt=""><img class="author-ghost-wafer" src="assets/native/layouts/pentimento-wafer.webp" alt=""><img class="author-ghost-content" src="assets/native/layouts/pentimento-pentimento-closed-content.webp" alt=""><img class="author-ghost-light" src="assets/native/layouts/pentimento-pentimento-closed-light.webp" alt=""><i class="author-activation author-activation-1"></i><i class="author-activation author-activation-2"></i><i class="author-activation author-activation-3"></i><i class="author-activation author-activation-4"></i></div><div class="author-ghost-veil"></div></div><div class="author-credit"><p class="eyebrow" data-credit="label">BUILT BY GENE</p><h2 id="author-statement" class="author-statement" data-credit="statement">The work is personal.<br><span>The standard isn’t.</span></h2><div class="author-identity"><p class="author-name" data-credit="name">Wei Gene Khor</p><span class="author-divider" aria-hidden="true">|</span><p class="author-domain" data-credit="domain">artifactsbygene.com</p></div><div class="author-links"><a href="mailto:weigenekhor@gmail.com" data-credit="email">Email ${icon('external',15)}</a><a href="https://www.linkedin.com/in/weigenekhor/" target="_blank" rel="noopener noreferrer" data-credit="linkedin">LinkedIn ${icon('external',15)}</a></div></div></section>
<footer class="ending page-width"><a href="#top" class="closing-identity"><img src="assets/brand/artifacts-symbol.svg" width="25" height="25" alt=""><span>ARTIFACTS</span></a><p>Built against inefficiency.</p></footer></main>
<dialog class="lightbox" id="capture-viewer" aria-labelledby="viewer-title"><div class="lightbox-bar"><div><h2 id="viewer-title"></h2><p id="viewer-caption"></p></div><div><span id="viewer-count"></span><button type="button" data-viewer-close aria-label="Close image viewer">${icon('close')}</button></div></div><div class="lightbox-stage"><button type="button" data-viewer-prev aria-label="Previous screenshot">${icon('back')}</button><div class="lightbox-image-wrap"><img id="viewer-image" alt=""><span class="image-loading" role="status" hidden>Loading capture…</span></div><button type="button" data-viewer-next aria-label="Next screenshot">${icon('next')}</button></div><div class="lightbox-footer"><span>Original application capture</span><a id="viewer-original" target="_blank" rel="noopener">Full resolution ${icon('external',16)}</a></div></dialog>
<noscript><style>.app-shell{pointer-events:none}.hero-sequence:after{display:none!important}.gallery-navigation button,.open-capture{display:none}.gallery-image{cursor:default}</style><p class="noscript-note page-width">Enable JavaScript to explore the product. All application captures remain available below.</p></noscript>
<script type="application/json" id="artifacts-data">${JSON.stringify(model).replaceAll('<','\\u003c')}</script><script type="application/json" id="native-layout-data">${JSON.stringify(homeLayouts)}</script><script type="application/json" id="native-panel-data">${JSON.stringify(panelReferences)}</script><script type="module" src="site.js"></script></body></html>`;
let output=html;
for(const file of ['tokens.css','site.css','shell.css','thinking.css','site.js']){
 const hash=createHash('sha256').update(await fs.readFile(file)).digest('hex').slice(0,10);
 output=output.replaceAll(`"${file}"`,`"${file}?v=${hash}"`);
}
await fs.writeFile('index.html',output);
console.log(`Built native ARTIFACTS: ${model.apps.length} applications, ${model.expeditions.length} Expeditions, ${model.apps.reduce((n,a)=>n+a.images.length,0)} screenshots.`);
