import {homeMarkup} from '../native-home.js';
export const esc=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export const icon=(name,size=20)=>{
 const paths={home:'M3 10 12 3l9 7v11h-6v-7H9v7H3Z',menu:'M3 5h18M3 12h18M3 19h18',external:'M8 4h12v12M20 4 5 19',minus:'M5 12h14',max:'M5 5h14v14H5Z',close:'m6 6 12 12M18 6 6 18',back:'m14 5-7 7 7 7',next:'m10 5 7 7-7 7',expand:'M4 9V4h5M15 4h5v5M20 15v5h-5M9 20H4v-5',pause:'M8 5v14M16 5v14',play:'m8 5 11 7-11 7Z'};
 return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.home}"/></svg>`;
};
const themes=()=>`<div class="theme-control" role="group" aria-label="Application theme">${['origin','pentimento'].map(t=>`<button type="button" data-theme-choice="${t}" aria-label="${t==='origin'?'Origin':'Pentimento'} theme" aria-pressed="${t==='pentimento'}"><span class="swatch ${t}-swatch"></span></button>`).join('')}</div>`;

export function nativeShell(model,layouts){
 const sidebar=model.expeditions.map(e=>e.apps.map(id=>{
  const a=model.apps.find(a=>a.id===id);
  return `<button type="button" data-inspect-app="${id}" data-mode="${e.mode}" aria-label="About ${esc(a.name)}"><img src="${a.navigationIcon}" width="18" height="18" alt=""><span>${esc(a.name)}</span></button>`;
 }).join('')).join('');
 const markup=`<div class="hero-sequence"><div class="product-stage"><div class="product-rig"><div class="product-viewport"><div class="app-shell" data-theme="pentimento" data-mode="pentimento" aria-label="Interactive ARTIFACTS application">
 <nav class="app-sidebar" aria-label="Application navigation"><div class="sidebar-brand"><a href="#top" class="title-logo" aria-label="ARTIFACTS"><img src="assets/brand/artifacts-symbol.svg" alt="" width="28" height="28"></a><span>ARTIFACTS</span></div><div class="sidebar-scroll"><button type="button" data-expand-nav aria-label="Expand application navigation" aria-expanded="false">${icon('menu')}<span>Hide</span></button><button type="button" data-home aria-label="Home" aria-current="page">${icon('home')}<span>Home</span></button><div class="sidebar-apps">${sidebar}</div><button class="sidebar-settings" type="button" data-settings aria-label="Application Info" aria-expanded="false"> <img src="assets/native/navigation/application-info.svg" width="18" height="18" alt=""><span>Application Info</span></button></div></nav>
 <aside class="settings-drawer" id="application-info" aria-label="Application Info" aria-hidden="true" inert><img data-info-image src="assets/native/panels/pentimento-info.webp" width="240" height="820" alt=""><div class="sr-only"><h3>Application Info</h3><p>${esc(model.softwareInfo.description)}</p><dl>${Object.entries(model.softwareInfo.details).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl></div></aside>
 <header class="app-titlebar"><div class="window-controls">${themes()}<button class="mode-control" type="button" data-cycle-mode aria-label="Switch to Legacy mode"><span data-mode-range>V–VI</span><span data-mode-name>Pentimento</span></button><a class="window-control website-control" href="#principle" aria-label="Explore the ARTIFACTS website">${icon('external')}</a><i class="control-divider" aria-hidden="true"></i>${['minus','max','close'].map((n,i)=>`<button type="button" class="window-control desktop-only" disabled aria-label="${['Minimize','Maximize','Close'][i]} (desktop only)">${icon(n)}</button>`).join('')}</div></header>
 <div class="app-content"><div class="app-home">${homeMarkup(model,layouts,'pentimento-pentimento-closed')}</div></div><footer class="app-status"><span>ARTIFACTS</span><span data-product-status>Pentimento</span></footer></div></div>
 <div class="product-toolbar"><span>Explore the applications</span><a href="#principle">Continue to explore <span aria-hidden="true">↓</span></a></div><label class="mobile-app-picker">Application information<select aria-label="Choose application information"><option value="">Select an application</option>${model.apps.map(app=>`<option value="${app.id}">${esc(app.name)}</option>`).join('')}</select></label></div></div></div>
 <aside class="module-details" id="module-details" role="region" aria-label="Application details" hidden><div class="module-details-scroll" tabindex="0" aria-label="Application information and preview"><div class="module-details-body"><img class="native-panel" alt=""><img class="native-panel-motion" alt="" hidden><div class="sr-only" data-panel-text></div></div></div><button type="button" data-close-details aria-label="Close application details">${icon('close',16)}</button></aside>`;
 return markup.replace(/<button(?![^>]*disabled)/g,'<button disabled');
}
