export const esc=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export const icon=(name,size=20)=>{
 const paths={home:'M3 10 12 3l9 7v11h-6v-7H9v7H3Z',menu:'M3 5h18M3 12h18M3 19h18',external:'M8 4h12v12M20 4 5 19',minus:'M5 12h14',max:'M5 5h14v14H5Z',close:'m6 6 12 12M18 6 6 18',back:'m14 5-7 7 7 7',next:'m10 5 7 7-7 7',expand:'M4 9V4h5M15 4h5v5M20 15v5h-5M9 20H4v-5',pause:'M8 5v14M16 5v14',play:'m8 5 11 7-11 7Z'};
 return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.home}"/></svg>`;
};
const themes=()=>`<div class="theme-control" role="group" aria-label="Application theme">${['origin','pentimento'].map(t=>`<button type="button" data-theme-choice="${t}" aria-label="${t==='origin'?'Origin':'Pentimento'} theme" aria-pressed="${t==='pentimento'}"><span class="swatch ${t}-swatch"></span></button>`).join('')}</div>`;

export function nativeShell(model,references){
 const homes=Object.entries(references).map(([key,ref])=>{
  const [theme,mode]=key.split('-');
  return `<div class="home-reference" data-home-theme="${theme}" data-home-mode="${mode}"><img class="home-render" src="assets/native/home/${key}-1161.webp" srcset="assets/native/home/${key}-1161.webp 1161w, assets/native/home/${key}.webp 2322w" sizes="(max-width:760px) 90vw, 1224px" width="1161" height="750" ${key==='pentimento-pentimento'?'fetchpriority="high"':'loading="lazy"'} alt="ARTIFACTS ${mode} homepage"><div class="home-hotspots">${ref.cards.map(card=>{
   const app=model.apps.find(a=>a.sourceKey===card.key),expedition=model.expeditions.find(e=>e.mode===mode&&e.apps.includes(app.id));
   return `<button type="button" class="app-tile" data-open-app="${app.id}" data-expedition="${expedition.id}" aria-label="Open ${esc(app.name)}" style="left:${card.x}px;top:${card.y}px;width:${card.width}px;height:${card.height}px;--hover-render:url('assets/native/home/${key}-${card.key}.webp')"><span class="sr-only">${esc(app.name)}</span></button>`;
  }).join('')}</div></div>`;
 }).join('');
 const sidebar=model.expeditions.map(e=>e.apps.map(id=>{
  const a=model.apps.find(a=>a.id===id);
  return `<button type="button" data-open-app="${id}" data-mode="${e.mode}" title="${esc(a.name)}" aria-label="Open ${esc(a.name)}"><img src="${a.navigationIcon}" width="18" height="18" alt=""><span>${esc(a.name)}</span></button>`;
 }).join('')).join('');
 return `<div class="product-stage"><div class="product-viewport"><div class="app-shell" data-theme="pentimento" data-mode="pentimento" data-view="home" aria-label="Interactive ARTIFACTS application">
 <header class="app-titlebar"><button class="title-logo" type="button" data-home aria-label="ARTIFACTS home"><img src="assets/brand/artifacts-symbol.svg" alt="" width="28" height="28"></button><span class="title-greeting">Artifacts for Gene</span><div class="window-controls">${themes()}<button class="mode-control" type="button" data-cycle-mode aria-label="Switch to Legacy mode"><span data-mode-range>V–VI</span><span data-mode-name>Pentimento</span></button><a class="window-control website-control" href="#principle" aria-label="Explore the ARTIFACTS website">${icon('external')}</a><i class="control-divider" aria-hidden="true"></i>${['minus','max','close'].map((n,i)=>`<button type="button" class="window-control" disabled aria-label="${['Minimize','Maximize','Close'][i]} (desktop only)">${icon(n)}</button>`).join('')}</div></header>
 <div class="app-body"><nav class="app-sidebar" aria-label="Application navigation"><button type="button" data-expand-nav aria-label="Expand application navigation" aria-expanded="false">${icon('menu')}<span>Navigation</span></button><button type="button" data-home aria-label="Home" aria-current="page">${icon('home')}<span>Home</span></button><div class="sidebar-apps">${sidebar}</div><button class="sidebar-settings" type="button" data-settings aria-label="Open application info" aria-expanded="false"><img src="assets/native/navigation/application-info.svg" width="18" height="18" alt=""><span>Application Info</span></button></nav><aside class="settings-drawer" aria-label="Application info" hidden><header><strong>Application Info</strong><button type="button" data-settings aria-label="Close application info">${icon('close',16)}</button></header><div class="settings-content"></div></aside><div class="app-content"><div class="app-home">${homes}</div></div></div><footer class="app-status"><span>ARTIFACTS</span><span data-mode-name>Pentimento</span></footer><aside class="module-details" hidden aria-label="Application details"></aside></div>
 <div class="product-capture" hidden><img alt="" decoding="async"><p class="capture-status" role="status" hidden></p></div><noscript><img class="product-static-home" src="assets/native/home/homepage-fallback.webp" width="6148" height="4100" alt="ARTIFACTS homepage"></noscript></div>
 <div class="product-toolbar"><div class="product-home-status"><span>Explore the application</span></div><div class="product-capture-controls" hidden><button type="button" data-product-home>${icon('back',16)} <span>Home</span></button><span data-product-name></span><div class="product-image-controls"><span data-product-count></span><button type="button" data-product-prev aria-label="Previous application capture">${icon('back',16)}</button><button type="button" data-product-next aria-label="Next application capture">${icon('next',16)}</button></div></div><a href="#principle">Continue to explore <span aria-hidden="true">↓</span></a></div>
 <label class="mobile-app-picker">Explore an application<select aria-label="Choose an application"><option value="">ARTIFACTS homepage</option>${model.apps.map(app=>`<option value="${app.id}">${esc(app.name)}</option>`).join('')}</select></label><span class="sr-only" data-shell-status role="status"></span></div>`;
}
