// Original monochrome instrument studies: layered work, connected checks, ordered evidence.
const face=(points,kind='instrument-face')=>`<polygon class="${kind}" points="${points}"/>`;
const slab=(x,y,w=119,d=59,h=10)=>`${face(`${x-w},${y} ${x},${y+d} ${x},${y+d+h} ${x-w},${y+h}`,'instrument-side')}${face(`${x},${y+d} ${x+w},${y} ${x+w},${y+h} ${x},${y+d+h}`,'instrument-front')}${face(`${x},${y-d} ${x+w},${y} ${x},${y+d} ${x-w},${y}`)}`;
const cube=(x,y,w,h,cls)=>`<g class="${cls}">${face(`${x-w},${y} ${x},${y+w*.5} ${x},${y+w*.5+h} ${x-w},${y+h}`,'instrument-side')}${face(`${x},${y+w*.5} ${x+w},${y} ${x+w},${y+h} ${x},${y+w*.5+h}`,'instrument-front')}${face(`${x},${y-w*.5} ${x+w},${y} ${x},${y+w*.5} ${x-w},${y}`)}<path class="instrument-detail" d="m${x-8} ${y-2} 8-4 8 4-8 4Z"/></g>`;
const frame=(title,body)=>`<svg viewBox="0 0 360 280" role="img" aria-label="${title}"><g class="reasoning-field" fill="none" stroke="currentColor" stroke-width=".85" stroke-linecap="round" stroke-linejoin="round">${body}</g></svg>`;
const layers=Array.from({length:6},(_,i)=>`<g class="instrument-layer layer-${i}">${slab(180,178-i*18)}</g>`).join('');
const plates=frame('Layered working surfaces with a wafer reference retained in the upper plate.',`${layers}<g class="retained-reference"><ellipse cx="180" cy="87" rx="43" ry="21" class="instrument-detail"/><path class="instrument-detail" d="M141 87h78m-68 8h58m-49 7h40M152 74l56 27m-35-34 45 22m-77-7 53 26"/><path class="reference-signal" pathLength="1" d="M141 87h78"/></g><path class="plate-edge" pathLength="1" d="m61 88 119 59 119-59"/>`);
const blocks=frame('Four distinct working blocks assembled around one shared structure.',`${cube(184,51,45,65,'block block-back')}${cube(93,112,47,70,'block block-left')}${cube(267,124,42,45,'block block-right')}<path class="structure-link" pathLength="1" d="m184 139-36 18 36 18 39-20"/>${cube(181,184,48,48,'block block-front')}<g class="block-check"><path d="m174 182 5 3 12-6" pathLength="1"/></g>`);
const sheets=Array.from({length:10},(_,i)=>{const x=167-i*12,y=199+i*4,h=142-i*12,w=104,dy=48;return `<g class="evidence-sheet sheet-${i}">${face(`${x},${y-h} ${x+w},${y-h+dy} ${x+w},${y+dy} ${x},${y}`)}<path class="sheet-return" d="m${x} ${y-h} 3-2 ${w} ${dy}v${h}l-3 2"/></g>`}).join('');
const evidence=frame('Evidence resolves into a graduated sequence of fine working planes.',`${sheets}<path class="evidence-signal" pathLength="1" d="m59 93 0 142 104 48"/>`);
export const principles=[
 {identifier:'FRICTION',name:'Start with the friction.',description:'Every tool begins with something that should work better: a repeated task, a difficult comparison, a hidden dependency, or a decision carrying too much manual effort.',handoff:'Turn recurring reasoning into a system.',figure:plates},
 {identifier:'STRUCTURE',name:'Make the repeatable explicit.',description:'Capture the checks that matter. Automate what does not need human attention. Preserve the context needed for the decisions that do.',handoff:'The work reveals what needs to improve next.',figure:blocks},
 {identifier:'REFINEMENT',name:'Refine through the work.',description:'Put the evidence, context, and next action where they can be understood together. Use the tool. Challenge it. Improve it as the process, data, and requirements change.',figure:evidence}
];
export const principleSection=()=>`<section class="principles page-width" id="principle" aria-labelledby="principle-heading"><p class="eyebrow">The thinking behind the tools</p><header class="thinking-preface"><h2 id="principle-heading"><span class="thesis-primary">Purpose-built from the work.</span> <span class="thesis-continuation">Less repetition. More room for engineering judgment.</span></h2><p class="thinking-context">ARTIFACTS does not begin with features.<br>It begins with something in the work that should be better.<span>Different problems, brought into one disciplined way of working.</span></p></header><div class="principle-cycle" data-motion="paused"><div class="principle-grid">${principles.map((p,i)=>`<figure class="principle-figure" data-reasoning="${i+1}"><p class="reasoning-identifier"><span>FIG. 0${i+1}</span><span>${p.identifier}</span></p><div class="principle-drawing">${p.figure}</div><figcaption><h3>${p.name}</h3><p>${p.description}</p>${p.handoff?`<p class="reasoning-handoff">${p.handoff}</p>`:''}</figcaption></figure>`).join('')}</div></div></section>`;
